server:
  port: 8080

# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      settings:
        web-allow-others: false
        trace: true
      enabled: true
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
#      data-locations: classpath:db/data-h2.sql


